### ISSUE TITLE
Not compatible with django-compressor

### ISSUE THREAD

**Issue by spapas** [EmilStenstrom/django-components#300] opened 2023-07-27 14:32 UTC
When I try to run `python manage.py compress` on a project that uses django-compressor (https://github.com/django-compressor/django-compressor/) I get the following error:

```
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\offline\django.py", line 84, in remove_block_nodes
    setattr(node, attr, sub_nodelist)
AttributeError: can't set attribute 'nodelist'
```

After some debugging it seems that django-compressor can't handle the component_block for example like this: 

```
      {% component_block "card" "Εμφάνιση στοιχείων" color="" header_color="bg-info" header_text_color="text-light" %}
        {% fill "body" %}
          {% for p in ac.object_lists %}
            <a class='btn btn-info mt-1' href='{% url "object-list-detail" p.0 %}'>{{ p.1 }}</a>
          {% endfor %}
        {% endfill %}
      {% endcomponent_block %}
```

I opend that issue on django-compressor (https://github.com/django-compressor/django-compressor/issues/1201) but it is probably easier to fix django-components instead ?

**Comment by EmilStenstrom** [comment] 2023-08-07 21:44
@spapas We're open to reviewing PR:s if you write one up! I think supporting django-compressor is worthwhile.

**Comment by spapas** [comment] 2023-08-08 06:11
Hey @EmilStenstrom i'd be happy to provide a PR for this but unfortunately I'm not sure how this shouled be fixed :(

**Comment by lemontheme** [comment] 2023-09-16 13:26
Just looking at this now. I've yet to investigate it properly, but the exception seems to occur because django-compressor tries to reassign the nodelist attribute. (I've never used django-compressor, so I'll have to read up on why it does this.) Anyway, the reassignment fails on `ComponentNode.nodelist` this class's `nodelist` is implemented as a getter method using the \@property decorator.

Next steps:

1. Figure out what django-compressor does and what the implications would be of letting it make attribute reassignments to our internal Node objects.
2. Re-implement `ComponentNode.nodelist` as a bona fide public attribute, since this would appear to more in line with what other tooling expects.

Link to relevant LoC: https://github.com/EmilStenstrom/django-components/blob/3318bde9c36c237fcf88a965332b915340281780/django_components/templatetags/component_tags.py#L405C1-L407C1

**Comment by dylanjcastillo** [comment] 2024-01-14 19:47
@spapas how are you using `django-compress` with `django-components`? 

I tried it and it worked well, including the offline compression.

For this file:

```html
{% load compress %}
<!DOCTYPE html>
<html>
<head>
    <title>django_components sample projects</title>
    {% compress css inline %}
    {% component_css_dependencies %}
    {% endcompress %}
</head>
<body>
    {% component "calendar" date=date %}
    {% compress js inline %}
    {% component_js_dependencies %}
    {% endcompress %}
</body>
</html>
```

I'd get the following output in the terminal:
```shell
(.venv) ➜  sampleproject git:(fix-django-compressor) ✗ python manage.py compress
Compressing... done
Compressed 2 block(s) from 2 template(s) for 1 context(s).
```

And this **manifest.json**:
```
{
  "09b06615770e91e1e0ecf96ae5e6440df322f602c3de93700df780f0dd350f03": "<style type=\"text/css\" media=\"all\">.calendar-component{width:200px;background:pink}.calendar-component span{font-weight:bold}</style>",
  "ceed0ea23040b95dac7dd2f7385d0ce335e597e5260f6144e03b5119975dfacf": "<script>(function(){if(document.querySelector(\".calendar-component\")){document.querySelector(\".calendar-component\").onclick=function(){alert(\"Clicked calendar!\");};}})();</script>"
}
```

**Comment by spapas** [comment] 2024-01-14 20:03
@dylanjcastillo the problem is with component blocks not with simple comonents. For example this won't work:

```html
  {% component_block "card" "Foo" %}
    {% fill "body" %}
      <div class='row'>
        <div class='col'>BAR</div>
      </div>
    {% endfill %}
  {% endcomponent_block %}
```

**Comment by dylanjcastillo** [comment] 2024-01-14 20:12
Could you provide a full example of how you use `django-compressor` with component blocks? 

I've only seen people use it to compress JS/CSS files.

**Comment by spapas** [comment] 2024-01-14 20:29
I don't use django-compressor with component blocks. The problem is that django-compressor will try to parse your templates to find the stuff it needs to compress. When it finds the component_block it doesn't like it and breaks.

**Comment by dylanjcastillo** [comment] 2024-01-14 21:22
I see. I was trying to work on this issue, but couldn't find a way to reproduce it.

FWIW, the calendar component in the example also used a component block: 

```html
<div class="calendar-component">
  <div>Today's date is <span>{{ date }}</span></div>
  <div>Your to-dos:</div>
  <ul>
    <li>
      {% component_block "todo" %}
        {% fill "todo_text" %}
          Stop forgetting the milk!
        {% endfill %}
      {% endcomponent_block %}
    </li>
    <li>
      {% component_block "todo" %}
        {# As of v0.28, 'fill' tag optional for 1-slot filling if component template specifies a 'default' slot #}
        Wear all-white clothes to laser tag tournament.
      {% endcomponent_block %}
    </li>
  </ul>
</div>
```

**Comment by spapas** [comment] 2024-01-14 21:25
And? Can you test if it breaks when django conpressor is used?

**Comment by dylanjcastillo** [comment] 2024-01-14 21:25
It works, that's what I meant

**Comment by spapas** [comment] 2024-01-14 21:26
Very strange... I'll try it again

**Comment by spapas** [comment] 2024-01-14 21:29
Can you try it with a component block only? Instead of the calendar add the todo component to your template.

**Comment by dylanjcastillo** [comment] 2024-01-15 09:20
It also works like that

**Comment by spapas** [comment] 2024-01-15 10:38
Unfortunately I still see the same error:

```
Traceback (most recent call last):
  File "C:\progr\py3\ehcg\ehcg\manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\management\base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\management\base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\management\commands\compress.py", line 370, in handle
    self.handle_inner(**options)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\management\commands\compress.py", line 395, in handle_inner
    offline_manifest, block_count, results = self.compress(
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\management\commands\compress.py", line 257, in compress
    nodes = list(parser.walk_nodes(template, context=context))
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\offline\django.py", line 161, in walk_nodes
    for node in self.walk_nodes(node, original, context):
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\offline\django.py", line 155, in walk_nodes
    for node in self.get_nodelist(node, original, context):
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\offline\django.py", line 135, in get_nodelist
    return handle_extendsnode(node, context)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\offline\django.py", line 40, in handle_extendsnode
    return handle_extendsnode(node, context)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\offline\django.py", line 47, in handle_extendsnode
    new_nodelist = remove_block_nodes(parent_nodelist, block_stack, block_context)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\offline\django.py", line 63, in remove_block_nodes
    expanded_block = expand_blocknode(node, block_stack, block_context)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\offline\django.py", line 94, in expand_blocknode
    expanded_nodelist = remove_block_nodes(block.nodelist, block_stack, block_context)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\offline\django.py", line 63, in remove_block_nodes
    expanded_block = expand_blocknode(node, block_stack, block_context)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\offline\django.py", line 94, in expand_blocknode
    expanded_nodelist = remove_block_nodes(block.nodelist, block_stack, block_context)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\offline\django.py", line 80, in remove_block_nodes
    sub_nodelist = remove_block_nodes(
  File "C:\progr\py3\ehcg\venv\lib\site-packages\compressor\offline\django.py", line 84, in remove_block_nodes
    setattr(node, attr, sub_nodelist)
AttributeError: can't set attribute 'nodelist'
```

```
django-components==0.31
django-compressor==4.4
```

Are you using different versions maybe ?

**Comment by dylanjcastillo** [comment] 2024-01-15 10:49
Same version it seems. 

```shell               
asgiref==3.7.2
Django==5.0.1
django-appconf==1.0.6
django-components==0.31
django-compressor==4.4
rcssmin==1.1.1
rjsmin==1.2.1
sqlparse==0.4.4
typing_extensions==4.9.0
```

If you provide a small reproducible repo with the error, I can probably check it out sometime this week.

**Comment by spapas** [comment] 2024-01-15 10:52
Thank you @dylanjcastillo I'll try to give you a repo that has the problem!

**Comment by spapas** [comment] 2024-01-15 11:30
Hey @dylanjcastillo I've created a minimal repository that reproduces the problem: https://github.com/spapas/components_compress

Please notice that in order for the problem to appear the component block must be on an extended template (see base.html and home.html on the repo)

**Comment by dylanjcastillo** [comment] 2024-01-19 15:20
Hi @spapas, I created a small fix for this issue. I tested it with your example and with django-components own testing suite. But I think it'd be worthwhile if you can test it on your own project to confirm that the issue is fixed.

Here's the branch with my changes: https://github.com/dylanjcastillo/django-components/tree/fix-django-compressor

**Comment by spapas** [comment] 2024-01-19 18:23
Hello @dylanjcastillo I just tested it and it works fine! 

Pinging @EmilStenstrom for merging the PR #364 and releasing a new ver.

Thank you for the help!

**Comment by EmilStenstrom** [comment] 2024-01-19 22:02
@spapas @dylanjcastillo Great collab, [0.33](https://pypi.org/project/django-components/) is now released with this fix!

**Closed by EmilStenstrom** 2024-01-19 22:02 UTC
Labels: bug, help wanted
