### ISSUE TITLE
Support for Paths as objects is missing

### ISSUE THREAD

**Issue by ldurey** [EmilStenstrom/django-components#522] opened 2024-06-04 07:07 UTC
Hello everyone,
First of all, thanks for you great work, this project seems like really useful for our team.
This is my first contribution to an open source project, so apologies if i'm not sufficiently clear. 

I wanted to report that the support for [Paths as objects](https://docs.djangoproject.com/en/5.0/topics/forms/media/#paths-as-objects) declaration is not possible with the current state of the `django_components` project.

## Context
- We are using a [ManifestStaticFilesStorage](https://docs.djangoproject.com/en/5.0/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.ManifestStaticFilesStorage) to manage our static files.
- We want to be able to use `Javascript module` declaration for rather complex components.

So we did a declaration of js asset like this
```
from django.templatetags.static import static
from django.utils.html import format_html

js = [format_html(f'<script type="module" src="{static(static_path)}"></script>')]
```
But in our case, this is clashing with `ManifestStaticFilesStorage` because the `static` call is evaluated at initialisation of the project. And the static files manifest may miss some keys for newly added files (not registered yet). So we end up with `ValueError` raised at init.
Because of that evaluation at initialisation we can't call `collectstatic` to populate the manifest which is actually needed to populate itself. (DEBUG = False must be used to raise the Exception, so this is a production only Bug.)

To solve this problem we tried to use `Paths as objects`, and this is the issue I report.

## Issue 
```
from django.templatetags.static import static
from django.utils.html import format_html, html_safe

@html_safe
class JSModulePath:
	def __init__(self, static_path):
		self.static_path = static_path 

	def __str__(self):
		return format_html(f'<script type="module" src="{static(self.static_path)}"></script>')

# Component
	js = [JSModulePath(static_path=static_path)]
```

With this asset declaration, we end up with a `TypeError` raised by `os.path.join()` at this [line of code](https://github.com/EmilStenstrom/django-components/blob/3a7d5355cfa5d37641a4c80ee9fd2423cea10c1b/src/django_components/component.py#L120).

## How to solve
Reading the code, it seems like all the problem come from support for relative path in assets declaration which is handled by this method [_resolve_component_relative_files](https://github.com/EmilStenstrom/django-components/blob/3a7d5355cfa5d37641a4c80ee9fd2423cea10c1b/src/django_components/component.py#L80C5-L80C38).
If I just comment this line, everything is all right and support for `Paths as objects` is back.

A quick fix I may think is a setting to allow or disallow relative paths for assets declaration with some documentation to point out that relative paths breaks support for `Paths as objects`.
Maybe something like this juste to elaborate a bit more : 

```
# settings.py
COMPONENTS = {
    "ALLOW_STATIC_RELATIVE_DECLARATION": False,  # with default to True to preserve compatibility. 
}
```
Utility function 
```
# components.py 
def is_static_relative_declaration_allowed() -> bool:
    return getattr(settings, "COMPONENTS", {}).get("ALLOW_STATIC_RELATIVE_DECLARATION", True)
```
Replace [that line](https://github.com/EmilStenstrom/django-components/blob/3a7d5355cfa5d37641a4c80ee9fd2423cea10c1b/src/django_components/component.py#L75C9-L75C49) by a conditional usage 
```
if is_static_relative_declaration_allowed():
	_resolve_component_relative_files(attrs) 
```

## Workaround for `JS module declaration` with `ManifestStaticFilesStorage` (not `Paths as objects`)
We implemented a workaround to detect which management command is running and we are escaping the `ValueError` except when we are running `runserver` to still have some feedback at runtime.
```
def script_as_module(static_path):
    if settings.RUNNING_RUNSERVER:
        return format_html(f'<script type="module" src="{static(static_path)}"></script>')
    else:
        try:
            return format_html(f'<script type="module" src="{static(static_path)}"></script>')
        except ValueError:
            return ''

# with this in setttings.py
RUNNING_RUNSERVER = (len(sys.argv) > 1 and 'runserver' in sys.argv)
```

## Finally
I guess this is just one solution among others and there is certainly a better way to go. (type checking or something like this, like Django actually does in `Media.render_dependencies` methods.)
Tell me if you need more informations or something else. I'm willing to contribute as much as I can to help you on this subject.

Have a great day !

**Comment by EmilStenstrom** [comment] 2024-06-04 20:39
@ldurey Hi! Your report was not clear at all. Happy that you found the project useful. Your use-case is rather esoteric, and I think adding a config to disable relative path resolution is not the right solution.

Idea: Could you make your custom class work with os.path.join instead of disabling it? Maybe you could simply inherit from Path in your custom class, and then magically everything would work?

**Comment by ldurey** [comment] 2024-06-05 08:26
Thanks for your reply, your idea is actually working for `os.path.join` compatibility with this solution : 
```
@html_safe
class JSModulePath(Path):
    _flavour = type(Path())._flavour

    def __init__(self, static_path):
        self.static_path = static_path 

    def __str__(self):
        return format_html(f'<script type="module" src="{static(self.static_path)}"></script>')

# component Media
js = [JSModulePath(static_path)]
```
But this is not solving the initial trouble with `ManifestStaticFilesStorage` because `_resolve_component_relative_files` is breaking the lazy behaviour by evaluating the string at initiation. Which can't be resolved correctly before `collectstatic` is fully completed.

I've found this solution which seems to be a more robust alternative to me : 
- Handle direct html declaration in resolve file (the idea come from [django implementation](https://github.com/django/django/blob/adae619426b6f50046b3daaa744db52989c9d6db/django/forms/widgets.py#L106)

I feel like `filepath` is not a `str` every time so maybe this test should be moved elsewhere. 
```
def resolve_file(filepath: str) -> str:
		if hasattr(filepath, '__html__'): # Added
			return filepath # Added

        maybe_resolved_filepath = os.path.join(comp_dir_abs, filepath)
        component_import_filepath = os.path.join(comp_dir_rel, filepath)

        if os.path.isfile(maybe_resolved_filepath):
            logger.debug(
                f"Interpreting template '{filepath}' of component '{module_name}' relatively to component file"
            )
            return component_import_filepath

        logger.debug(
            f"Interpreting template '{filepath}' of component '{module_name}' relatively to components directory"
        )
        return filepath
```

What do you think about it ?

**Comment by EmilStenstrom** [comment] 2024-06-05 20:33
Hi, I'm not sure what the solution is here? I've looked at that code three times and at the implementation we have in master. Is it the same code, or did you change anything?

My suggestion is this: Fork this repository, add a test for your use-case, and then add a fix that makes your test pass, and that doesn't break any of our tests. Open a PR, and let us take a look. Then we can easily see what you changed. Sounds like a deal?

**Comment by JuroOravec** [comment] 2024-06-09 09:35
@ldurey Do I understand correctly that the end goal is to:

1. Format the scripts tags as:
	```
	<script type="module" src="{static(static_path)}"></script>
	```
2. Do so lazily, so only at the point where the file path is being formatted into the script tag above, so that it doesn't conflict with collection of static file?

I think there should be a way to achieve your goals without turning off the relative path resolution.

---

I just had a look at the file resolution logic, and I think this issue touches on 3 separate things:
1. Support Django's "Path as Object" use case
2. Allow to configure how the JS / CSS paths should be formatted into tags.
3. Allow to turn off / opt out of the relative path resolution

### 1. Support Django's "Path as Object" use case

This should be done on our side, so that paths can be defined as strings (`__str__()`), os.PathLike & pathlib.Path (`__fspath__()`), Django's PathObject (`__html__()`) and possibly bytes (`__bytes__()`.

### 2. Allow to configure how the JS / CSS paths should be formatted into tags.

While we could handle `<script type="module" ...>` inside django_components, I'm that maybe a better way would be if anyone could format the script tags however they want.

E.g. the API could look like this:

```py
class MyComponent(component.Component):
	class Media:
		js = "abc.js"

		# Taken from Django's Media, but with extra `type="module"` added
	    def render_js(self):
	        return [
	            (
	                path.__html__()
	                if hasattr(path, "__html__")
	                else format_html('<script type="module" src="{}"></script>', self.absolute_path(path))
	            )
	            for path in self._js
	        ]
```

In this example above, my suggestion is that if the `class Media` doesn't inherit from any class, than internally we'd make it to inherit from Django's Media class by default. So it would be the same as we write:
```py
	class Media(django.forms.widgets.Media):
```

That means that if you wanted to reuse your custom `render_js` function, you could reuse it as so:
```py
class MyMedia(django.forms.widgets.Media):
    def render_js(self):
        return [
            (
                path.__html__()
                if hasattr(path, "__html__")
                else format_html('<script type="module" src="{}"></script>', self.absolute_path(path))
            )
            for path in self._js
        ]

class MyComponent(component.Component):
	class Media(MyMedia):
		js = "abc.js"
```

Alternatively, maybe, we could define the custom Media class on the Component class via `media_class` attribute:
```py
class MyComponent(component.Component):
	media_class = MyMedia
	class Media:
		js = "abc.js"
```

In the example above, we would internally instantiate `MyMedia` as:
```py
MyMedia(js=MyComponent.Media.js, css=MyComponent.Media.css)
```

So `MyComponent.Media` would define only `js` and `css` properties, and nothing more, as it is now. So the component's API remains clean.

TBH, personally I prefer this second approach with `media_class`, because with the first approach (`MyComponent.Media.render_js`), it would  be less explicit and could lead to some ambiguity.

### 3. Allow to turn off / opt out of the relative path resolution

If the other two features addressed the needs of this issue, then I think adding option to disable relative path resolution is lower in priority.

**Comment by JuroOravec** [comment] 2024-06-09 20:27
I got a working version + tests for working with "paths as objects" and making it easy to override the `render_js` and `render_css` methods of Django's `Media`.

However, I feel like this still won't resolve @ldurey's problem, because even if a path is given as an object, we resolve it on the spot at component class creation. So if first all components need to be collected before the file path can be resolved to a string, than that's a problem.

I wonder if we could resolve that on the level of individual files, e.g.:

1. `Media.js_dynamic` / `Media.css_dynamic` properties to declare JS/CSS files that will be resolved only at render time.
```py
class MyComponent(component.Component):
	class Media:
		js = "path/to/my_script.js"
		js_dynamic = [JSModulePath(static_path)]
```

2. Or same but on the level of Media:
```py
class MyComponent(component.Component):
	class Media:
		js = "path/to/my_script.js"
	class DynamicMedia:
		js = JSModulePath(static_path)
```

2. Or same but on the level of files:
```py
# Similar to `mark_safe`
def mark_dynamic(file):
	file.__dynamic__ = lambda self: True
	return file

class MyComponent(component.Component):
	class Media:
		js = [
			"path/to/my_script.js",
			mark_dynamic(static_path),
		]
```

**Comment by sfourestier** [comment] 2024-06-10 09:03
Hello everyone,
Thanks a lot for your reactivity.
Sorry, ldurey is exceptionally busy for at least one week.
Although I have less time (so I will be a bit less reactive), I can replace ldurey during his absence.
After JuroOravec replies, is it still relevant to fork the repository so as to present ldurey solution?
I can also test JuroOravec "paths as objects" code.
Please, let me know, how I can help efficiently.

**Comment by EmilStenstrom** [comment] 2024-06-11 05:02
@JuroOravec I think we're still inheriting from Django's Form Assent base class? There the statiticfiles magic is handled automatically: https://docs.djangoproject.com/en/5.0/topics/forms/media/#paths-in-asset-definitions - I wonder if we should copy this behavior?

**Comment by JuroOravec** [comment] 2024-06-11 20:14
@EmilStenstrom  Not sure if I understand, but looking at the link you've posted, I think we could resolve the issue that I posted in my previous message by NOT resolving the "path objects".

So, in other words, if component's JS/CSS files are specified as `str`, `bytes`, `pathlib.Path`, `PathLike`, then we try to resolve these are relative paths. But if the JS/CSS files are set as the "path object" with `@html_safe`, then we DO NOT try to resolve these as relative files.

---

@sfourestier If you're happy with the solution I've suggested here, then no. But if you would have other features or issues, than yes :) Either way, tho, I'd still be really helpful to have a minimal example for how your django project is set up. Since I don't use `ManifestStaticFilesStorage` in my project, it's hard for me to say if what I'm suggesting here is really addressing your issue.

**Comment by EmilStenstrom** [comment] 2024-06-11 20:23
@JuroOravec Sorry for being unclear. The third example from the link above shows how relative paths work with [ManifestStaticFilesStorage](https://docs.djangoproject.com/en/5.0/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.ManifestStaticFilesStorage) is configured: They resolve it to the correct path for use with staticfiles. If we would do the same, we wouldn't have to deal with lazy path objects, and the call to static wouldn't be needed.

Makes sense?

**Comment by JuroOravec** [comment] 2024-06-12 07:08
Right, thanks I think I understand. So we wouldn't have to deal with the question of "how and which media files to evaluate at render time" because if we did the similar logic that staticfiles does, then @ldurey wouldn't have to call `static()`:

```py
f'<script type="module" src="{static(static_path)}"></script>'
```

And instead they could just do:

```py
<script type="module" src="{static_path}"></script>'
```

(assuming that `static_path` in the second example would be already resolved by us.

So the piece of code you had in mind was probably [this one](https://github.com/django/django/blob/f812b927a541fecc8ee445e1fd4dbe9d0540d523/django/templatetags/static.py#L125)?

---

On a different note, I lost the changes I made to support paths as objects 😭 at least tests remained. But that means I'll give this another go next weekend the soonest.

**Comment by JuroOravec** [comment] 2024-06-12 21:13
Ok, I've re-implemented it, and pushed it online so it won't be lost again. @EmilStenstrom Could you have a look when you have time to check if I understood correctly how to handle that `static()`?

Also @sfourestier and @ldurey, could you share the Django settings that you use with `ManifestStaticFilesStorage`? So I could write tests based on that.

**Comment by EmilStenstrom** [comment] 2024-06-13 05:20
@JuroOravec I'm actually not sure what code path is best. But let's set up a test like you are hinting at, and see that the code is behaving logically :)

**Comment by sfourestier** [comment] 2024-06-13 14:58
Hello @JuroOravec,
Here is some code to reproduce the bug (I wrote it by removing some code on `django-polls` django tutorial and adding your documentation first component : `calendar`) :
[django-polls.zip](https://github.com/user-attachments/files/15822016/django-polls.zip)

### 1 Working code
```
cd django-polls
pip install -r requirements.txt
python manage.py runserver --insecure  # We use insecure to serve staticfiles with DEBUG = FALSE
```
We can access to :
http://127.0.0.1:8000/polls/
and see the calendar component.

### 2 Reproduce the issue
Now if you uncomment the last line in `mysite/settings.py` :
```
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
```
And run `python manage.py collectstatic`, you get:
```
ValueError: Missing staticfiles manifest entry for 'calendar/script.js'
```
This is the issue would resolve.

### 3 A basic workaround
If you comment `components/calendar/calendar.py:19`, a workaround will skip the exception during `collectstatic` :
```
python manage.py collectstatic
128 static files copied to '/home/sebastien/tmp/django-polls/static_root', 128 post-processed.
```
Now, after `python manage.py runserver`, you can access to http://127.0.0.1:8000/polls/

(In this test case, static files are not served, because unfortunely, `--insecure` does [not work with ManifestStaticFilesStorage](https://docs.djangoproject.com/en/5.0/ref/contrib/staticfiles/#cmdoption-runserver-insecure)), and I did not taken the time to improve that configuration. Has right urls are computed, I think it is suffisent to validate a fix, however, if you need a more complete test, I can work on that)

### 4 Test a fix (summary)
To test a fix you can :
1. uncomment `components/calendar/calendar.py:19`,
2. delete staticfiles folder : `rm -rf static_root`
3. run `python manage.py collectstatic` to reproduce the error
4. update `components.calendar.calendar.script_as_module` to obtain `<script type="module" src="{static(static_path)}"></script>` in the template, without `ValueError` exception

→ I hope this help, if it is unclear or not relevant, let me know, I will go more deeply into the issue.

**Comment by JuroOravec** [comment] 2024-06-13 15:04
@sfourestier thanks for that! I'll try to go through it this weekend

**Comment by JuroOravec** [comment] 2024-06-14 07:30
Had a quick play with the example. 

I followed the instructions steps 1 and 2, (I also deleted `static_root` before running `collectstatic`). And I used my local  copy of django_components (slightly modified version of https://github.com/EmilStenstrom/django-components/pull/526)

I got the solution where:
1. One can run `python manage.py collectstatic` with `ManifestStaticFilesStorage ` without an error
2. Browser uses the hashed versions of JS/CSS e.g.:
	```html
	<script type="module" src="/static/calendar/script.e1815e23e0ec.js"></script>
	```
3. One can modify how the JS/CSS tags are rendered (e.g. in the example above, we've added `type="module"`.

There's two ways one will be able to achieve this. In both cases we modify the `components/calendar/calendar.py` file:

### Example 1 - Overriding `Media.render_js` to add `type="module"` to ALL script tags:

NOTE: In this example, Django's `Media.absolute_path` calls `static()` for us, so no need to call it explicitly.

```py
from django.forms.widgets import Media

class MyMedia(Media):
    # Same as original Media.render_js, except the `<script>` tag has also `type="module"`
    def render_js(self):
        return [
            path.__html__()
            if hasattr(path, "__html__")
            else format_html('<script type="module" src="{}"></script>', self.absolute_path(path))
            for path in self._js
        ]

@component.register("calendar")
class Calendar(component.Component):
    template_name = "calendar/template.html"

    def get_context_data(self, date):
        return {
            "date": date,
        }

    media_class = MyMedia
    class Media:
        css = "calendar/style.css"
        js = ["calendar/script.js"]
```

### Example 2 - Define lazily-evaluated [SafeData/SafeString](https://docs.djangoproject.com/en/5.0/_modules/django/utils/safestring/) object as path to add `type="module"` to SINGLE script tags:

```py
class PathObj:
    def __init__(self, static_path: str) -> None:
        self.static_path = static_path
    def __html__(self):
        return format_html(f'<script type="module" src="{static(self.static_path)}"></script>')

@component.register("calendar")
class Calendar(component.Component):
    template_name = "calendar/template.html"

    def get_context_data(self, date):
        return {
            "date": date,
        }

    class Media:
        css = "calendar/style.css"
        js = [PathObj("calendar/script.js")]
```

---

However, there is still one issue remaining, but I'm not sure if that's an issue on my part or Django's. Django seems to be unable to find with the hashed static files even though they exist.

When I navigate to http://127.0.0.1:8000/polls, I can see that the browser links to the hashed files:

```html
<html>
  <head>
    <link href="/static/calendar/style.0eeb72042b59.css" media="all" rel="stylesheet">
  </head>
  <body cz-shortcut-listen="true">
    <div class="calendar-component">
      Today's date is <span>2015-06-19</span>
    </div>
    <script type="module" src="/static/calendar/script.e1815e23e0ec.js"></script>
  </body>
</html>
```

But in the terminal, I see that the requests for JS/CSS returned 404:

<img width="660" alt="Screenshot 2024-06-13 at 22 15 38" src="https://github.com/EmilStenstrom/django-components/assets/25986782/fd1b5305-7155-49b3-b452-b9b55052ebe7">

Even though these files ARE in the `static_root/calendar` folder:

<img width="280" alt="Screenshot 2024-06-14 at 09 07 15" src="https://github.com/EmilStenstrom/django-components/assets/25986782/4df8e23e-7333-426b-8ecd-bde43e1a9d07">

Any ideas why this is so? Or whether this is relevant only to dev server (`runserver`)?

**Comment by sfourestier** [comment] 2024-06-14 08:26
Hello @JuroOravec,

Thanks, for your reactivity on the two solutions/examples.

Regarding, the issue remaining, it is relevant of my test case. It have not read enough documentation/spend time to solve it. I suppose that when you use `ManifestStaticFilesStorage`, the static files cannot be served with the development server (this is because of that I spoke about `ManifestStaticFilesStorage` and `--insecure` incompatibility).

Regarding the solutions, maybe I prefer the example 2 robustness because it rely on an official [Paths as objects](https://docs.djangoproject.com/en/5.0/topics/forms/media/#paths-as-objects) django interface.
Thus I think that #526 fix this issue.
→ II will try it with #526 code in our production architecture, to validate that everything is fine. I will then reply another comment.

**Comment by JuroOravec** [comment] 2024-06-14 09:04
Hey @sfourestier, thanks for the proactivity! Heads up that I just now pushed updates to #526

**Comment by sfourestier** [comment] 2024-06-14 12:20
Sorry, we have a bug to solve to before allowing upgrading to `django-components-0.80` and I have not enough time to fix it today.
Please wait until next week for the test of your solution/pull request.
Best

**Comment by ldurey** [comment] 2024-06-17 14:29
Hey, I'm back to follow this issue, sorry I had a family issue to solve last week.

@JuroOravec, your PR #526 works perfectly fine with our production settings as long as we use your implementation of Path as Objects :
```
from django.templatetags.static import static
from django.utils.html import format_html

class PathObj:
    def __init__(self, static_path: str) -> None:
        self.static_path = static_path

    def __html__(self):
        return format_html(f'<script type="module" src="{static(self.static_path)}"></script>')
```

But, we cannot use ["django's" style](https://docs.djangoproject.com/en/5.0/topics/forms/media/#paths-as-objects) which is : 
```
from django.templatetags.static import static
from django.utils.html import format_html, html_safe

@html_safe 
class PathObj:
    def __init__(self, static_path: str) -> None:
        self.static_path = static_path

    def __str__(self):
        return format_html(f'<script type="module" src="{static(self.static_path)}"></script>')
```
I feel like it's wrong if we cannot use Django documentation directly to build dependencies.

The bug now come from this [line of code only](https://github.com/EmilStenstrom/django-components/pull/526/files#diff-bdb1917504a9c50a51e7fdf49498d5db3ce0233be9eb81b13938d4b3dcd5efc3R335) which is forcing evaluation of the `str` value of `filepath`.
This `str` value is implemented in the django's way to write so it raise a bug.
But it is not in your way to write it (so it's using `repr` and give a object representation which does not raise a bug)

To fix this you can add the repr() evaluation like this (i don't how useful is this logger.debug report) : 
```
    logger.debug(
        f"Interpreting template '{repr(filepath)}' of component '{module_name}' relatively to components directory"
    )
```

I'm working on a PR based on yours to create a Test and show my fix.

**Comment by JuroOravec** [comment] 2024-06-17 15:39
Hey @ldurey, hope everything is well with your family 🙏 

Thanks for spotting that bug, I've updated the said logger statements to use `repr`.

I also added your way of defining the object path to the tests.

I've pushed the updates to https://github.com/EmilStenstrom/django-components/pull/526/files. Let me know if everything works now :)

**Comment by ldurey** [comment] 2024-06-18 06:59
Thanks for your concern.

Everything works now, thank you.

Just to say, i can't verify that the tests are actually triggering on failure (we will keep one on our side).
I didn't success to trigger an exception from your TestCases by modifying the code, but i'm not used to `tox`.
I'm looking to do this with github action as we did in our project, but again that's a failure because forking is locking me i think.
I'm still working on it.

**Comment by ldurey** [comment] 2024-06-18 07:30
It seems i can't trigger github actions myself on this repository, so i wrote the check we use in our project to verify that everything is fine.
You can find the code [here](https://github.com/EmilStenstrom/django-components/pull/530/files/be1f6a1ad8897a51a317f386c28df19d23220a11..9a3eaa6008ff0b9b09cdea51ebf0b6874be4fff2) in PR #530 .
I can't verify that it works as it, but i think it should.

If the workflow work as expected then you can remove the  [if statement] (https://github.com/EmilStenstrom/django-components/pull/526/files#diff-bdb1917504a9c50a51e7fdf49498d5db3ce0233be9eb81b13938d4b3dcd5efc3R323) and it should raise the error we found.

Hope this helps.

**Comment by JuroOravec** [comment] 2024-06-18 13:09
@ldurey Thanks, I had a look at your changes. I added a test to ensure that we don't trigger the `__html__`/`__str__` methods of path objects during class creating (see https://github.com/EmilStenstrom/django-components/pull/526/commits/025649b21029113eb30c413a6d9c2c8b46c9b25a). That is similar to running `collectstatic`, just taking a different approach so it can be integrated as a unit test, instead of adding a github action.

There's also unit tests for using the manifest filesystem (https://github.com/EmilStenstrom/django-components/pull/526/files#diff-7667a514b72a24c770553fe3421223dcc03252c458518310f25a5ef7746d4669R629). IMO together they should ensure that things are working as expected!

**Closed** 2024-06-21 17:36 UTC

**Comment by JuroOravec** [comment] 2024-06-21 17:48
Hey @ldurey and @sfourestier, thanks for the help! This has now been released in https://github.com/EmilStenstrom/django-components/releases/tag/0.82  :)
