### ISSUE TITLE
runserver hot reload doesn't work on django 5 when component's python file is modified

### ISSUE THREAD

**Issue by Snakeyyy** [EmilStenstrom/django-components#191] opened 2022-11-23 19:21 UTC
**Problem**
It seems that on django 3.2 (I haven't tested other versions) django development server is not reloaded when component's python file is modified.

On django 4.1 hot reloading works correctly. 

Testid with `django-components==0.22`

**Steps to reproduce:**

1. clone django-components repository
2. modify `sampleproject/requirements.txt`: freeze django to version 3.2 `django==3.2`
3. install requirements `pip install -r requirements.txt`
4. run the project `python3 manage.py migrate && python3 manage.py runserver`
5. update file `sampleproject/components/calendar/calendar.py` (eg. add `raise Exception('hello')` inside method `get_context_data`
6. Refresh the page in the browser and observe that change is not propagated (eg. the exception is not raised)
7. Kill the runserver command and run it again to confirm that in this case the change is propagated (eg. the exception is raised)

**Comment by EmilStenstrom** [comment] 2022-11-24 11:46
Great bug report, I had no idea. Agreed that this should be fixed. Especially since this affects the developer experience with components, something I find important to get right.

Would you be open to working on a fix for this? I guess it has something to do with having Django find the relevant files, and mark them so that the file watcher finds them?

**Comment by Snakeyyy** [comment] 2022-11-25 17:56
I've already spent a few hours investigating but unfortunately I couldn't find the solution.

My observations so far:

django.utils.autoreload sees the file change, it's visible from django logging (DEBUG level):

This is a log record from django 3.2: 
```
django-components/sampleproject/components/calendar/calendar.py notified as changed. Signal results: [(<function template_changed at 0x10229a0e0>, True), (<function translation_file_changed at 0x102b4e950>, None)].
```

compared to django 4.1 which results in a slightly different log record:
```
django-components/sampleproject/components/calendar/calendar.py notified as changed. Signal results: [(<function template_changed at 0x106510280>, None), (<function translation_file_changed at 0x106da7ac0>, None)].
```

I'm worried that even if we identify e.g commit that fixes this for django 4 it will be challenging to prepare a fix as the auto-reloading component is hard to extend with custom logic.

I've tested also Django 3.1 (hot reloading NOT working) and 4.0 (hot reloading IS working)  

My ideas about next steps:
- state this issue as a known issue in documentation
- we can test whether it works when watchman is used instead of statreloader and eventually recommend to use watchman as workaround
- identify which commit exactly fixes this issue and eventually try to prepare fix based on that

**Comment by EmilStenstrom** [comment] 2022-11-25 20:27
Thanks for researching! Let me see if I can continue where you left off:

1. The template_changed event pointed me to this stackoverflow answer: https://stackoverflow.com/a/71618373/117268
2. This points to this Change in Django: https://code.djangoproject.com/ticket/32744
3. I think this comment sums it up well: https://code.djangoproject.com/ticket/32744#comment:6
4. And based on this I think we should try to normalize all paths in 'DIRS' to absolute Path() objects. 

Do you have some time to test this with your setup, to see if this fixes things?

**Comment by TawalMc** [comment] 2022-11-27 19:52
Hi. Just to add that I'm using Django 4.x in some projects and hot reload work perfectly but with the same versions hot reload doesn't work with django-components... I don't know if it's related to django-components... can I help ?

**Comment by EmilStenstrom** [comment] 2022-11-27 21:04
Tawal: Could you try setting you TEMPLATES DIRS setting to not be strings, and instead use Path(path).resolve() and see if it works in Django 3.2?

**Comment by EmilStenstrom** [comment] 2022-11-29 20:35
I don't understand how everything fits together yet, but it seems the cached template loader was changed to be on by default in django 4.1, and additionally was made to reload on template changes when debug was true. Reference: https://twitter.com/carltongibson/status/1588534399561510914

**Comment by EmilStenstrom** [comment] 2023-11-24 18:03
I'm afraid we don't have the bandwidth to deal with this bug, so I'm going to close it. For people encountering this, please upgrade your django version.

**Comment by liquidiert** [comment] 2024-04-05 07:53
Sorry to reopen this but I have the same issue in django 5.0.4 :/ I always have to restart the runserver command.
What I tried so far:
- remove the `django_components.template_loader.Loader` in settings -> did nothing
- add django-browser-reload -> It triggers a browser reload on save but the component updates are not reflected

Has anyone experienced the same with django-browser-reload and django-components?

**Comment by EmilStenstrom** [comment] 2024-04-05 09:57
@liquidiert Makes sense to open since this affects the latest Django version.

**Comment by liquidiert** [comment] 2024-04-05 10:37
Nice, do you need any more information? @EmilStenstrom

**Comment by EmilStenstrom** [comment] 2024-04-05 10:49
@liquidiert I don't have the bandwidth to troubleshoot this atm. Anything you can do to narrow down the problem is helpful.

Questions:
* Could you create a simple testcase the reproduces this?
* django-browser-reload shouldn't be needed to reproduce this, just saving the file in your editor should reload in the terminal where you have manage.py runserver running. Is nothing happening in the terminal?
* Does it matter where you put the components? I think I've seen STATICFILES_DIRS being handled differently, so try moving it out of this directory.

**Comment by liquidiert** [comment] 2024-04-05 11:11
@EmilStenstrom I will come up with a testcase soon. Regarding your questions:
- I nailed it down to single file components not working. Once I split the components it works like a charm!
- The files have to be in the dir I defined in STATICFILES_DIR otherwise it does not work / component not registered error gets thrown

**Comment by liquidiert** [comment] 2024-04-05 12:12
Sounds good to me! @EmilStenstrom

**Closed** 2024-04-05 12:40 UTC
Labels: bug, help wanted
